from backend.app.ai.prompts.system_prompts import (
    KHOJAI_AGENT_SYSTEM_PROMPT,
    INTENT_DETECTION_SYSTEM_PROMPT,
    CONTEXT_SYNTHESIS_TEMPLATE,
)

__all__ = [
    "KHOJAI_AGENT_SYSTEM_PROMPT",
    "INTENT_DETECTION_SYSTEM_PROMPT",
    "CONTEXT_SYNTHESIS_TEMPLATE",
]
