"""Custom Trip Planning, Day-by-Day Route Itinerary, and User Travel Preferences."""

import uuid
from datetime import date
from typing import Any, Dict, List, Optional
from sqlalchemy import (
    Boolean,
    CheckConstraint,
    Date,
    ForeignKey,
    Index,
    Integer,
    JSON,
    String,
    Text,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.types import UUID

from backend.app.database.base import (
    Base,
    ProvenanceMixin,
    TimestampMixin,
    UUIDPrimaryKeyMixin,
)


class Trip(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    """Custom trip plan configured by a traveler or generated by the AI assistant."""

    __tablename__ = "trips"

    user_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
        doc="Owner user identifier if saved/claimed",
    )

    destination_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("destinations.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
        doc="Primary anchor destination",
    )

    share_token: Mapped[str] = mapped_column(
        String(64),
        unique=True,
        index=True,
        default=lambda: uuid.uuid4().hex[:16],
        nullable=False,
        doc="URL-safe shareable token",
    )

    title: Mapped[str] = mapped_column(
        String(200),
        nullable=False,
        doc="Trip title (e.g. 'Apatani Cultural Immersion & High Trails')",
    )

    description: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
        doc="Trip overview narrative",
    )

    start_date: Mapped[Optional[date]] = mapped_column(
        Date,
        nullable=True,
        doc="Target travel start date",
    )

    end_date: Mapped[Optional[date]] = mapped_column(
        Date,
        nullable=True,
        doc="Target travel end date",
    )

    total_days: Mapped[int] = mapped_column(
        Integer,
        default=5,
        nullable=False,
        doc="Duration in days",
    )

    budget_tier: Mapped[str] = mapped_column(
        String(20),
        default="₹₹",
        nullable=False,
        doc="Budget tier: '₹', '₹₹', '₹₹₹'",
    )

    status: Mapped[str] = mapped_column(
        String(30),
        default="draft",
        nullable=False,
        doc="Status: 'draft', 'confirmed', 'completed', 'archived'",
    )

    is_public: Mapped[bool] = mapped_column(
        Boolean,
        default=False,
        nullable=False,
        doc="Whether trip is accessible via public share link",
    )

    # Relationships
    days: Mapped[List["TripDay"]] = relationship(
        "TripDay",
        back_populates="trip",
        cascade="all, delete-orphan",
        order_by="TripDay.day_number",
    )

    destination: Mapped[Optional["Destination"]] = relationship(
        "Destination",
        back_populates="trips",
    )

    user: Mapped[Optional["User"]] = relationship(
        "User",
        back_populates="trips",
    )

    __table_args__ = (
        CheckConstraint("total_days >= 1 AND total_days <= 60", name="ck_trips_total_days"),
        Index("idx_trips_user_status", "user_id", "status"),
        Index("idx_trips_share_token", "share_token"),
    )

    def __repr__(self) -> str:
        return f"<Trip id={self.id} title='{self.title[:30]}' days={self.total_days}>"


class TripDay(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    """Specific day in a planned trip with sequenced schedule items."""

    __tablename__ = "trip_days"

    trip_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("trips.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        doc="Foreign key to parent trip",
    )

    day_number: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        doc="Sequential day order (1, 2, 3...)",
    )

    day_date: Mapped[Optional[date]] = mapped_column(
        Date,
        nullable=True,
        doc="Calendar date corresponding to this day",
    )

    theme_title: Mapped[str] = mapped_column(
        String(200),
        nullable=False,
        doc="Day theme or focus (e.g. 'Arrive in Ziro & Settle into Hong Village')",
    )

    notes: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
        doc="Logistics notes, buffer timing, or packing reminders",
    )

    # Relationships
    trip: Mapped["Trip"] = relationship(
        "Trip",
        back_populates="days",
    )

    items: Mapped[List["TripItem"]] = relationship(
        "TripItem",
        back_populates="trip_day",
        cascade="all, delete-orphan",
        order_by="TripItem.sort_order",
    )

    __table_args__ = (
        Index("idx_trip_days_trip_day", "trip_id", "day_number"),
    )

    def __repr__(self) -> str:
        return f"<TripDay trip_id={self.trip_id} day={self.day_number} title='{self.theme_title[:25]}'>"


class TripItem(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    """Specific scheduled stop, accommodation stay, meal, or transit leg."""

    __tablename__ = "trip_items"

    trip_day_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("trip_days.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        doc="Foreign key to parent trip day",
    )

    item_type: Mapped[str] = mapped_column(
        String(30),
        nullable=False,
        doc="Item category: 'attraction', 'activity', 'hotel', 'restaurant', 'transit', 'custom'",
    )

    # Optional references to structured database entities
    attraction_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("attractions.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    hotel_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("hotels.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    restaurant_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("restaurants.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    activity_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("activities.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )

    title: Mapped[str] = mapped_column(
        String(200),
        nullable=False,
        doc="Stop headline or title",
    )

    description: Mapped[Optional[str]] = mapped_column(
        Text,
        nullable=True,
        doc="Descriptive instructions or timing details",
    )

    start_time: Mapped[Optional[str]] = mapped_column(
        String(20),
        nullable=True,
        doc="Target start time (e.g. '09:00 AM')",
    )

    end_time: Mapped[Optional[str]] = mapped_column(
        String(20),
        nullable=True,
        doc="Target end time (e.g. '12:30 PM')",
    )

    estimated_cost: Mapped[Optional[str]] = mapped_column(
        String(50),
        nullable=True,
        doc="Estimated expense (e.g. '₹500')",
    )

    sort_order: Mapped[int] = mapped_column(
        Integer,
        default=1,
        nullable=False,
        doc="Chronological sequencing order within day",
    )

    # Relationships
    trip_day: Mapped["TripDay"] = relationship(
        "TripDay",
        back_populates="items",
    )

    attraction: Mapped[Optional["Attraction"]] = relationship("Attraction")
    hotel: Mapped[Optional["Hotel"]] = relationship("Hotel")
    restaurant: Mapped[Optional["Restaurant"]] = relationship("Restaurant")
    activity: Mapped[Optional["Activity"]] = relationship("Activity")

    __table_args__ = (
        Index("idx_trip_items_day_order", "trip_day_id", "sort_order"),
    )

    def __repr__(self) -> str:
        return f"<TripItem type='{self.item_type}' title='{self.title[:25]}'>"


class UserTravelPreference(Base, UUIDPrimaryKeyMixin, TimestampMixin):
    """Personalized traveler profile, pacing preferences, and dietary requirements."""

    __tablename__ = "user_travel_preferences"

    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        unique=True,
        nullable=False,
        index=True,
        doc="Foreign key to user account (1:1)",
    )

    budget_preference: Mapped[str] = mapped_column(
        String(10),
        default="₹₹",
        nullable=False,
        doc="Target budget tier: '₹', '₹₹', '₹₹₹'",
    )

    preferred_pace: Mapped[str] = mapped_column(
        String(20),
        default="balanced",
        nullable=False,
        doc="Pacing: 'unhurried', 'balanced', 'intense'",
    )

    travel_styles: Mapped[List[str]] = mapped_column(
        JSON,
        default=lambda: ["Slow travel", "Culture-led"],
        nullable=False,
        doc="Preferred styles: ['Slow travel', 'Outdoors', 'Culture-led', 'Road trip']",
    )

    dietary_needs: Mapped[str] = mapped_column(
        String(50),
        default="none",
        nullable=False,
        doc="Dietary constraints: 'strictly_vegetarian', 'jain', 'local_traditional', 'none'",
    )

    fitness_level: Mapped[str] = mapped_column(
        String(30),
        default="moderate",
        nullable=False,
        doc="Physical activity comfort: 'light', 'moderate', 'active_trekker'",
    )

    preferred_stay_types: Mapped[List[str]] = mapped_column(
        JSON,
        default=lambda: ["Homestay", "Eco-Lodge"],
        nullable=False,
        doc="Preferred accommodations: ['Homestay', 'Eco-Lodge', 'Heritage Haveli']",
    )

    preferred_regions: Mapped[List[str]] = mapped_column(
        JSON,
        default=lambda: ["Himalayas", "Northeast"],
        nullable=False,
        doc="Preferred Indian geographic regions",
    )

    # Relationships
    user: Mapped["User"] = relationship(
        "User",
        back_populates="travel_preference",
    )

    def __repr__(self) -> str:
        return f"<UserTravelPreference user_id={self.user_id} pace='{self.preferred_pace}'>"
