import { ArrowLeft, ArrowUpRight, CalendarDays, Car, ChevronRight, CircleAlert, Coffee, Home, Leaf, MapPin, ShieldCheck, Utensils, Waves } from "lucide-react";
import { Link, useRoute } from "wouter";
import { ArrowLink, DestinationCard, SectionKicker, Shell, TrustBreakdown, TrustScore } from "@/components/site";
import { getDestination, destinations } from "@/data/destinations";

export default function DestinationDetail() {
  const [, params] = useRoute("/destination/:slug");
  const destination = getDestination(params?.slug ?? "ziro");
  const nearby = destinations.filter((item) => item.slug !== destination.slug).slice(0, 3);
  const details = [["Why go?", "For a slower rhythm, big green views and the kind of local hospitality that makes a place feel less like a stop and more like a story.", Leaf], ["Best time", `${destination.bestSeason} · Check current local conditions before you travel.`, CalendarDays], ["How to reach", "Illustrative route notes will be connected to live access data in a future version.", Car], ["Estimated budget", `${destination.budget} · Approx. ₹12,000–18,000 for 5 days in this demo scenario.`, Waves], ["Where to stay", "Community stay, small guesthouse or homestay — availability is not live in this MVP.", Home], ["Local food", "Ask locally, eat seasonally and leave room for a meal you did not plan for.", Utensils]] as const;
  return <Shell><main className="pt-[76px]"><section className="relative overflow-hidden bg-ink text-white"><img src={destination.image} alt={`${destination.name} landscape`} className="absolute inset-0 h-full w-full object-cover opacity-55" /><div className="absolute inset-0 bg-gradient-to-t from-ink via-ink/35 to-ink/10" /><div className="container relative flex min-h-[570px] flex-col justify-end pb-12 pt-20 md:min-h-[650px] md:pb-16"><Link href="/discover" className="absolute left-5 top-8 inline-flex items-center gap-2 text-xs font-semibold text-white/65 transition hover:text-white md:left-12"><ArrowLeft size={15} /> Back to discover</Link><div className="max-w-4xl"><div className="mb-5 flex flex-wrap gap-2"><span className="rounded-full border border-white/25 bg-white/10 px-3 py-1.5 text-[10px] font-mono uppercase tracking-[.16em] text-white/75">{destination.region}</span><span className="rounded-full border border-white/25 bg-white/10 px-3 py-1.5 text-[10px] font-mono uppercase tracking-[.16em] text-white/75">Community verified · demo</span></div><h1 className="font-display text-7xl tracking-[-.08em] md:text-9xl">{destination.name}</h1><div className="mt-4 flex flex-wrap items-center gap-4 text-sm text-white/70"><span className="flex items-center gap-2"><MapPin size={15} className="text-saffron-light" /> {destination.state}, India</span><span className="h-1 w-1 rounded-full bg-white/35" />{destination.tags.map((tag) => <span key={tag}>{tag}</span>)}</div><div className="mt-8 flex flex-wrap items-center gap-3"><TrustScore score={destination.trustScore} /><Link href="/planner" className="inline-flex items-center gap-2 rounded-full bg-white px-4 py-2.5 text-xs font-semibold text-ink transition hover:-translate-y-0.5 hover:bg-saffron-light">Plan a trip here <ArrowUpRight size={14} /></Link></div></div></div></section>
      <section className="container py-16 md:py-24"><div className="grid gap-14 lg:grid-cols-[1.1fr_.75fr] lg:items-start"><div><SectionKicker>Destination intelligence · Demo</SectionKicker><h2 className="max-w-2xl font-display text-5xl leading-[1] tracking-[-.06em] md:text-6xl">A place that asks you to <em className="text-olive">stay curious.</em></h2><p className="mt-7 max-w-2xl text-base leading-8 text-ink/65">{destination.description} This destination page is structured to make context visible before a traveller decides whether a place fits them.</p><div className="mt-10 grid gap-px overflow-hidden rounded-[22px] border border-line bg-line sm:grid-cols-2">{details.map(([title, body, Icon]) => <div key={title} className="bg-white p-6"><Icon size={18} className="text-saffron" /><h3 className="mt-5 text-sm font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-ink/55">{body}</p></div>)}</div><div className="mt-7 rounded-[22px] border border-saffron/25 bg-saffron/5 p-5"><div className="flex gap-3"><CircleAlert size={17} className="mt-0.5 shrink-0 text-saffron" /><div><p className="text-sm font-semibold text-ink">Travel with context</p><p className="mt-1 text-xs leading-5 text-ink/55">{destination.demoNote} Local access, weather, permissions and community guidance should always be verified close to departure.</p></div></div></div></div><div className="lg:sticky lg:top-28"><TrustBreakdown score={destination.trustScore} metrics={destination.trustMetrics} /><div className="mt-5 rounded-[24px] bg-ink p-6 text-white"><p className="font-mono text-[10px] uppercase tracking-[.2em] text-saffron-light">Community pulse</p><p className="mt-4 font-display text-3xl leading-tight tracking-[-.04em]">“A little more time here is almost always a good idea.”</p><p className="mt-5 text-xs text-white/45">Pattern from 18 illustrative notes · demo only</p></div></div></div></section>
      <section className="bg-mist py-16 md:py-20"><div className="container"><div className="mb-8 flex items-end justify-between gap-4"><div><SectionKicker>Keep looking around</SectionKicker><h2 className="font-display text-4xl tracking-[-.05em]">Nearby, not identical.</h2></div><ArrowLink href="/discover">See all places</ArrowLink></div><div className="grid gap-5 md:grid-cols-3">{nearby.map((item) => <DestinationCard key={item.slug} destination={item} />)}</div></div></section></main></Shell>;
}
